env:
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.5
language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION
#  - python setup.py -q install
# -r requirements.txt
# command to run tests
script:
  - python https://github.com/chk6622/SDMProject/src/manage.py test --settings=SDMProject.test_settings --verbosity=1